import { SportsEvent } from '../types/canonical';

export const INITIAL_EVENTS: SportsEvent[] = [
  {
    id: 'ufo:mtch:demo-eng-cro',
    sportId: '00',
    sportName: 'Football',
    tournament: 'UEFA Nations League',
    category: 'International',
    homeTeam: 'England',
    awayTeam: 'Croatia',
    isLive: true,
    clock: '68m',
    score: { home: 1, away: 1 },
    stats: { attacks: 104, dangerousAttacks: 67, possession: 52 },
    hasLiveRoom: true,
    activeRoomParticipants: 489,
    markets: [
      {
        id: 'm-1x2',
        name: 'Full Time Winner',
        category: 'MAIN',
        status: 'OPEN',
        selections: [
          { id: 'sel-eng-1', name: '1 (England)', odds: 2.10, trend: 'STEADY' },
          { id: 'sel-eng-x', name: 'X (Draw)', odds: 3.10, trend: 'STEADY' },
          { id: 'sel-eng-2', name: '2 (Croatia)', odds: 3.40, trend: 'UP' },
        ],
      },
      {
        id: 'm-goals',
        name: 'Total Goals',
        category: 'GOALS',
        status: 'OPEN',
        selections: [
          { id: 'sel-eng-u25', name: 'Under 2.5 Goals', odds: 1.85, trend: 'STEADY' },
          { id: 'sel-eng-o25', name: 'Over 2.5 Goals', odds: 1.95, trend: 'DOWN' },
        ],
      },
    ],
  },
  {
    id: 'ufo:mtch:1vu-03k',
    sportId: '00',
    sportName: 'Football',
    tournament: 'UEFA Champions League',
    category: 'Europe',
    homeTeam: 'Real Madrid',
    awayTeam: 'Inter Milan',
    isLive: true,
    clock: '74m',
    score: { home: 2, away: 1 },
    stats: { attacks: 88, dangerousAttacks: 54, possession: 58 },
    hasLiveRoom: true,
    activeRoomParticipants: 342,
    markets: [
      {
        id: 'm-1x2',
        name: 'Full Time Winner',
        category: 'MAIN',
        status: 'OPEN',
        selections: [
          { id: 'sel-1', name: '1 (Real Madrid)', odds: 1.65, trend: 'STEADY' },
          { id: 'sel-x', name: 'X (Draw)', odds: 4.70, trend: 'DOWN' },
          { id: 'sel-2', name: '2 (Inter Milan)', odds: 5.50, trend: 'UP' },
        ],
      },
      {
        id: 'm-goals',
        name: 'Total Goals',
        category: 'GOALS',
        status: 'OPEN',
        selections: [
          { id: 'sel-u35', name: 'Under 3.5 Goals', odds: 1.80, trend: 'STEADY' },
          { id: 'sel-o35', name: 'Over 3.5 Goals', odds: 1.95, trend: 'UP' },
        ],
      },
      {
        id: 'm-btts',
        name: 'Both Teams To Score',
        category: 'MAIN',
        status: 'OPEN',
        selections: [
          { id: 'sel-btts-y', name: 'Yes', odds: 1.45, trend: 'STEADY' },
          { id: 'sel-btts-n', name: 'No', odds: 2.60, trend: 'DOWN' },
        ],
      },
    ],
  },
  {
    id: 'ufo:mtch:1vu-06f',
    sportId: '00',
    sportName: 'Football',
    tournament: 'UEFA Youth League',
    category: 'Europe',
    homeTeam: 'Porto U19',
    awayTeam: 'Man. City U19',
    isLive: true,
    clock: '82m',
    score: { home: 3, away: 1 },
    stats: { attacks: 95, dangerousAttacks: 62, possession: 51 },
    hasLiveRoom: true,
    activeRoomParticipants: 118,
    markets: [
      {
        id: 'm-1x2',
        name: 'Full Time Winner',
        category: 'MAIN',
        status: 'OPEN',
        selections: [
          { id: 'sel-p1', name: '1 (Porto U19)', odds: 1.27, trend: 'DOWN' },
          { id: 'sel-px', name: 'X (Draw)', odds: 3.80, trend: 'STEADY' },
          { id: 'sel-p2', name: '2 (Man City U19)', odds: 17.00, trend: 'UP' },
        ],
      },
      {
        id: 'm-goals',
        name: 'Total Goals',
        category: 'GOALS',
        status: 'OPEN',
        selections: [
          { id: 'sel-u45', name: 'Under 4.5 Goals', odds: 1.35, trend: 'STEADY' },
          { id: 'sel-o45', name: 'Over 4.5 Goals', odds: 2.85, trend: 'UP' },
        ],
      },
    ],
  },
  {
    id: 'ufo:mtch:1vu-03g',
    sportId: '00',
    sportName: 'Football',
    tournament: 'UEFA Champions League',
    category: 'Europe',
    homeTeam: 'Borussia Dortmund',
    awayTeam: 'Villarreal',
    isLive: false,
    clock: 'Tomorrow 20:45',
    hasLiveRoom: true,
    activeRoomParticipants: 84,
    markets: [
      {
        id: 'm-1x2',
        name: 'Full Time Winner',
        category: 'MAIN',
        status: 'OPEN',
        selections: [
          { id: 'sel-d1', name: '1 (Dortmund)', odds: 1.90, trend: 'STEADY' },
          { id: 'sel-dx', name: 'X (Draw)', odds: 4.20, trend: 'STEADY' },
          { id: 'sel-d2', name: '2 (Villarreal)', odds: 4.30, trend: 'STEADY' },
        ],
      },
    ],
  },
  {
    id: 'ufo:mtch:1vu-0x1',
    sportId: '0x',
    sportName: 'Tennis',
    tournament: 'US Open',
    category: 'Grand Slam',
    homeTeam: 'Alcaraz C.',
    awayTeam: 'Shelton B.',
    isLive: true,
    clock: 'Set 2 (6-4, 3-2)',
    score: { home: 1, away: 0 },
    hasLiveRoom: true,
    activeRoomParticipants: 215,
    markets: [
      {
        id: 'm-winner',
        name: 'Match Winner',
        category: 'MAIN',
        status: 'OPEN',
        selections: [
          { id: 'sel-a1', name: '1 (Alcaraz)', odds: 1.22, trend: 'STEADY' },
          { id: 'sel-a2', name: '2 (Shelton)', odds: 4.10, trend: 'UP' },
        ],
      },
    ],
  },
];
